<?php
/*
 * Implements hook_menu.
 */
function menu_magic_menu() {
    $items = array();

    //Add magic link to side Navigation menu
    $items['magic'] = array(
        'title' => 'A little magic', //no need to wrap in t() since it's a menu title
        'page callback' => 'menu_magic_basic', //Name of php function we want Drupal to call when /magic is hit
        //'access callback' => 'user_access', //user_access drupal core defined function to check page-access rights
        //Don't even need above line when we use default core Drupal user_access function
        'access arguments' => array('access content'), //Passed in to user_access function: user_access('access content')
    );

    //Demonstrates wildcard use and dynamic path, navigate to /magic/*anything*
    $items['magic/%'] = array( //% is the Drupal wildcard character - user can type anything they want
        'title' => 'Even more magical',
        'page callback' => 'menu_magic_extra',
        'page arguments' => array(1), //Values passed into menu_magic_extra as arguments, 1 represents placement of %
        'access arguments' => array('access content'),
        'file' => 'menu_magic.extra.inc', //Signals that def of menu_magic_extra will live in given file
    );

    //Add Magic tab on user account page
    $items['user/%/magic'] = array( //% will be wildcard for user ID in this case
        'title' => 'Magic',
        'description' => 'Magical magic for users',
        'page callback' => 'menu_magic_user_tab',
        'page arguments' => array(1),
        'access arguments' => array('administer users'), //Only users with 'administer users' permission can view
        'file' => 'menu_magic.user.inc',
        'type' => MENU_LOCAL_TASK, //Defines type of menu item -> In this case rendered as tab
    );

    //Add Magic link in contextual menu for nodes
    $items['node/%node/magic'] = array( //Associated with every node, %node implicity passes in node_load(%) to callback
        'title' => 'Magic',
        'description' => 'Do amazing and magical things',
        'page callback' => 'menu_magic_node_context',
        'page arguments' => array(1),
        'access arguments' => array('access content'),
        'file' => 'menu_magic.context.inc',
        'type' => MENU_LOCAL_TASK,
        'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE, //Allows us to turn this item into a contextual link and as tab
    );

    return $items;
}

/*
 * Call back function for menu_magic.
 * Returns the content of the page
 */
function menu_magic_basic() {
    $content = array();

    //Very, very simple page element. It will appear on the page,
    //but other modules can't customize it and themes can't override its markup.
    $content['raw_markup'] = array(
        '#type' => 'markup',
        '#markup' => 'Truly, this is magical',
        '#prefix' => '<p>',
        '#suffix' => '</p>',
    );

    $variables = array(
        'path' => 'http://placekitten.com/440/400',
        'alt' => t('This is a magical kitten'),
        'title' => t('A cute kitten!'),
    );
    $content['themed-data'] = array(
        '#type' => 'markup',
        '#markup' => theme('image', $variables), //Generates themed output - not preferrable method
                                                //Instead, see the use of #theme property key below which is preferred
        '#prefix' => '<div class="menu-magic-image">', //Wrap in div with class to apply css to
        '#suffix' => '</div>',
        '#attached' => array( //Property which allows us to attach css/js to particular element
            'css' => array(
                drupal_get_path('module', 'menu_magic') . '/menu_magic.css', //drupal_get_path returns filepath to menu_magic module
            ), //This only loads into the browser when needed! Cool stuff
        ),
    );

    $content['renderable_element'] = array(
        '#theme' => 'item_list', //Drupal calls function theme_item_list to render the element
        '#title' => t('How do we know it\'s magic?'),
        '#items' => array( //Argument to theme_item_list function -> Drupal allows us to add as property to render array
            t("Is it made of wood?"),
            t("Does it sink in water?"),
            t("Does it weigh the same as a duck?"),
            t('The current time is %time.', array('%time' => date('r'))), //Display current date/time to demonstrate caching
        ),
        '#cache' => array(
            'keys' => array('menu_magic', 'renderable_element'), //menu_magic:renderable_element is the key in the cache
            'bin' => 'cache', //cache is the generic cache table created by Drupal
            'expire' => time() + 30, //Expires 30 seconds from now
            'granularity' => DRUPAL_CACHE_PER_PAGE, //bit-mapped constant which we can define cache per page, per role, etc
        ),
    );

    return $content;
}